name: Build Rainbond allinone
on:
  repository_dispatch:
    types:
      - GitHub
      - GitLab

jobs:
  build-ui:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        env:
          BUILD_RBD_APP_UI: false
          TRAVIS_PULL_REQUEST: false
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          if [ ${{ github.event.action }} == 'GitHub' ];then
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-ui.git
          else
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-ui-cloud.git
          fi
          cd rainbond-ui
          chmod +x ./build.sh
          ./build.sh

  build-rainbond-allinone:
    needs: build-ui
    runs-on: ubuntu-18.04
    steps:
      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 yapf==0.26.0

      - name: Pull code and Build allinone image
        env:
          VERSION: ${{ github.event.client_payload.version }}
          TRAVIS_PULL_REQUEST: false
          DOMESTIC_NAMESPACE: ${{ secrets.DOMESTIC_NAMESPACE }}
          DOMESTIC_DOCKER_PASSWORD: ${{ secrets.DOMESTIC_DOCKER_PASSWORD }}
          DOMESTIC_DOCKER_USERNAME: ${{ secrets.DOMESTIC_DOCKER_USERNAME }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          IMAGE_NAMESPACE: ${{ secrets.IMAGE_NAMESPACE }}
          DOMESTIC_BASE_NAME: ${{ secrets.DOMESTIC_BASE_NAME }}
          ADAPTOR_BRANCH: ${{ secrets.ADAPTOR_BRANCH}}
        run: |
          if [ ${{ github.event.action }} == 'GitHub' ];then
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-console.git
          else
            git clone -b ${{ github.event.client_payload.branch }} ${{ github.event.client_payload.clone_url }}/rainbond-console-cloud.git
          fi
          cd rainbond-console
          chmod +x  ./release.sh
          ./release.sh allinone
